server:
  port: 6920

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/epidemic_new
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

tencent:
  appId: ${oss.appId}
  secretId: ${oss.secretId}
  secretKey: ${oss.secretKey}
  region: ${oss.region}
  photoBucket: ${oss.photoBucket}



mybatis-plus:
  mapper-locations: classpath:mapper/*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
